// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Jason Ricca

//! Software-emulated PIV backend.
//!
//! `SwPivBackend` answers `PivBackend` operations against an Ed25519
//! keypair (slot 9C, signing) and an X25519 keypair (slot 9D, key
//! management / decrypt) generated by `tools/gen-dev-piv-keys` and
//! baked into the binary at compile time via `include_bytes!`. Not a
//! security boundary — keys live in process memory; production builds
//! select `CcidPivBackend` (stream B) where the secret never leaves
//! the YubiKey.
//!
//! ## DPIV v1 secret file layout (168 bytes)
//!
//! ```text
//!   [0..4]    magic = "DPIV"
//!   [4]       version = 0x01
//!   [5..8]    reserved
//!   [8..72]   slot-9C Ed25519 secret key (64 bytes seed||pubkey)
//!   [72..104] slot-9D X25519 secret scalar (32 bytes)
//!   [104..136] slot-9C Ed25519 public key  (32 bytes)
//!   [136..168] slot-9D X25519 public key   (32 bytes)
//! ```
//!
//! ## PIN policy
//!
//! Dev PIN is the standard PIV factory default `123456`. Three
//! consecutive failed verify attempts lock the backend; recovery
//! requires restarting the service (mimics a card reset). Sign /
//! decrypt require `verified == true`; get_pubkey / list_slots /
//! health / attest do not.

use super::PivBackend;
use cambios_libsys::keystore::{
    Ed25519Signature, MAX_PIV_SLOTS, MAX_PUBKEY_LEN, PivAlgo, PivError, PivHealthState,
    PivPubkey, PivSlot, PivSlotInfo, PivSlotList,
};

const DPIV_RAW: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/dev_piv_secret.bin"
));

const DPIV_MAGIC: &[u8; 4] = b"DPIV";
const DPIV_VERSION_V1: u8 = 1;
const DPIV_V1_SIZE: usize = 168;

const DEV_PIN: &[u8] = b"123456";
const MAX_PIN_FAILURES: u8 = 3;

pub struct SwPivBackend {
    ed25519_sk_bytes: [u8; 64],
    x25519_sk_bytes: [u8; 32],
    ed25519_pk_bytes: [u8; 32],
    x25519_pk_bytes: [u8; 32],
    verified: bool,
    pin_failures: u8,
}

impl SwPivBackend {
    /// Parse the DPIV v1 bundle and construct the backend in
    /// unverified state.
    ///
    /// `Err(PivError::WireFormat)` covers any DPIV-file shape error
    /// (wrong magic, wrong version, wrong length). Production callers
    /// treat this as a fatal boot error — the dev-piv build cannot
    /// run without a valid key file.
    pub fn from_dpiv_bundle(raw: &[u8]) -> Result<Self, PivError> {
        if raw.len() != DPIV_V1_SIZE {
            return Err(PivError::WireFormat);
        }
        if &raw[0..4] != DPIV_MAGIC {
            return Err(PivError::WireFormat);
        }
        if raw[4] != DPIV_VERSION_V1 {
            return Err(PivError::WireFormat);
        }
        let mut backend = SwPivBackend {
            ed25519_sk_bytes: [0u8; 64],
            x25519_sk_bytes: [0u8; 32],
            ed25519_pk_bytes: [0u8; 32],
            x25519_pk_bytes: [0u8; 32],
            verified: false,
            pin_failures: 0,
        };
        backend.ed25519_sk_bytes.copy_from_slice(&raw[8..72]);
        backend.x25519_sk_bytes.copy_from_slice(&raw[72..104]);
        backend.ed25519_pk_bytes.copy_from_slice(&raw[104..136]);
        backend.x25519_pk_bytes.copy_from_slice(&raw[136..168]);
        Ok(backend)
    }

    /// Convenience: load the compiled-in DPIV blob.
    pub fn from_compiled_in() -> Result<Self, PivError> {
        Self::from_dpiv_bundle(DPIV_RAW)
    }

    fn require_verified(&self) -> Result<(), PivError> {
        if self.pin_failures >= MAX_PIN_FAILURES {
            return Err(PivError::PinLocked);
        }
        if !self.verified {
            return Err(PivError::AuthRequired);
        }
        Ok(())
    }
}

impl PivBackend for SwPivBackend {
    fn health(&self) -> PivHealthState {
        if self.pin_failures >= MAX_PIN_FAILURES {
            // Card present but unusable until restart.
            PivHealthState::NotReady
        } else if self.verified {
            PivHealthState::Ready
        } else {
            PivHealthState::AuthRequired
        }
    }

    fn verify_pin(&mut self, pin: &[u8]) -> Result<(), PivError> {
        if self.pin_failures >= MAX_PIN_FAILURES {
            return Err(PivError::PinLocked);
        }
        // Constant-time-style comparison is not load-bearing for the dev
        // backend (the PIN is `123456` printed in the source) but matches
        // production's expected shape.
        let matched = pin.len() == DEV_PIN.len()
            && pin.iter().zip(DEV_PIN.iter()).fold(0u8, |acc, (a, b)| acc | (a ^ b)) == 0;
        if matched {
            self.verified = true;
            self.pin_failures = 0;
            Ok(())
        } else {
            self.pin_failures = self.pin_failures.saturating_add(1);
            self.verified = false;
            if self.pin_failures >= MAX_PIN_FAILURES {
                Err(PivError::PinLocked)
            } else {
                Err(PivError::AuthRequired)
            }
        }
    }

    fn list_slots(&self) -> PivSlotList {
        let mut list = PivSlotList {
            count: 0,
            entries: [PivSlotInfo {
                slot: PivSlot::Authentication,
                algo: PivAlgo::Ed25519,
                populated: false,
            }; MAX_PIV_SLOTS],
        };
        // SwPivBackend populates 9C (Ed25519 signing) + 9D (X25519
        // decrypt) only. 9A and 9E are reported as standard PIV slots
        // exist-but-empty so consumers calling `list_slots` see the
        // full v1 cap surface.
        list.entries[0] = PivSlotInfo {
            slot: PivSlot::Authentication,
            algo: PivAlgo::Ed25519,
            populated: false,
        };
        list.entries[1] = PivSlotInfo {
            slot: PivSlot::Signature,
            algo: PivAlgo::Ed25519,
            populated: true,
        };
        list.entries[2] = PivSlotInfo {
            slot: PivSlot::KeyManagement,
            algo: PivAlgo::X25519,
            populated: true,
        };
        list.entries[3] = PivSlotInfo {
            slot: PivSlot::CardAuthentication,
            algo: PivAlgo::Ed25519,
            populated: false,
        };
        list.count = 4;
        list
    }

    fn get_pubkey(&self, slot: PivSlot) -> Result<PivPubkey, PivError> {
        let (algo, pk) = match slot {
            PivSlot::Signature => (PivAlgo::Ed25519, &self.ed25519_pk_bytes),
            PivSlot::KeyManagement => (PivAlgo::X25519, &self.x25519_pk_bytes),
            PivSlot::Authentication | PivSlot::CardAuthentication => {
                return Err(PivError::SlotEmpty);
            }
        };
        let mut bytes = [0u8; MAX_PUBKEY_LEN];
        bytes[..32].copy_from_slice(pk);
        Ok(PivPubkey {
            algo,
            len: 32,
            bytes,
        })
    }

    fn sign(&self, slot: PivSlot, msg: &[u8]) -> Result<Ed25519Signature, PivError> {
        self.require_verified()?;
        if slot != PivSlot::Signature {
            return Err(PivError::WrongAlgorithm);
        }
        let sk = ed25519_compact::SecretKey::from_slice(&self.ed25519_sk_bytes)
            .map_err(|_| PivError::Generic)?;
        let sig = sk.sign(msg, None);
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());
        Ok(Ed25519Signature(sig_bytes))
    }

    fn decrypt(
        &self,
        slot: PivSlot,
        wrapped: &[u8],
        out: &mut [u8],
    ) -> Result<usize, PivError> {
        self.require_verified()?;
        if slot != PivSlot::KeyManagement {
            return Err(PivError::WrongAlgorithm);
        }
        // The "wrapped" payload is the caller's ephemeral X25519 public
        // key. Our 9D operation computes the ECDH shared secret; the
        // caller HKDFs it into a symmetric key and AES-decrypts the
        // outer envelope. Matches real PIV slot 9D semantics — the card
        // never sees the wrapped symmetric key, only the ephemeral pk.
        if wrapped.len() != 32 {
            return Err(PivError::Generic);
        }
        if out.len() < 32 {
            return Err(PivError::Generic);
        }
        let their_pk = ed25519_compact::x25519::PublicKey::from_slice(wrapped)
            .map_err(|_| PivError::Generic)?;
        let our_sk = ed25519_compact::x25519::SecretKey::from_slice(&self.x25519_sk_bytes)
            .map_err(|_| PivError::Generic)?;
        let shared = their_pk.dh(&our_sk).map_err(|_| PivError::Generic)?;
        out[..32].copy_from_slice(shared.as_ref());
        Ok(32)
    }

    fn attest(&self, _slot: PivSlot, _out: &mut [u8]) -> Result<usize, PivError> {
        // The software backend does not produce attestation certs.
        // Returning SLOT_EMPTY signals "no attestation available" to
        // callers without forcing an empty-cert allocation. A future
        // CcidPivBackend will return the YubiKey's on-card attestation
        // X.509 cert.
        Err(PivError::SlotEmpty)
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use cambios_libsys::keystore::PivStatus;

    // Each test constructs a fresh backend to keep PIN state isolated.
    fn fresh_backend() -> SwPivBackend {
        SwPivBackend::from_compiled_in().expect("dev_piv_secret.bin should parse")
    }

    fn verified_backend() -> SwPivBackend {
        let mut b = fresh_backend();
        b.verify_pin(DEV_PIN).expect("DEV_PIN should verify");
        b
    }

    #[test]
    fn loads_compiled_in_bundle() {
        let b = SwPivBackend::from_compiled_in().expect("parse");
        // Sanity: keys are not zero (would mean parse landed in the
        // wrong offset).
        assert!(b.ed25519_pk_bytes.iter().any(|&x| x != 0));
        assert!(b.x25519_pk_bytes.iter().any(|&x| x != 0));
    }

    fn assert_parse_err(raw: &[u8], expected: PivError) {
        // Avoid `unwrap_err` so SwPivBackend doesn't need Debug.
        match SwPivBackend::from_dpiv_bundle(raw) {
            Ok(_) => panic!("expected parse error, got Ok"),
            Err(e) => assert_eq!(e, expected),
        }
    }

    #[test]
    fn rejects_wrong_magic() {
        let mut bad = [0u8; DPIV_V1_SIZE];
        bad[0..4].copy_from_slice(b"XXXX");
        bad[4] = DPIV_VERSION_V1;
        assert_parse_err(&bad, PivError::WireFormat);
    }

    #[test]
    fn rejects_wrong_version() {
        let mut bad = [0u8; DPIV_V1_SIZE];
        bad[0..4].copy_from_slice(DPIV_MAGIC);
        bad[4] = 0xFF;
        assert_parse_err(&bad, PivError::WireFormat);
    }

    #[test]
    fn rejects_wrong_length() {
        let bad = [0u8; DPIV_V1_SIZE - 1];
        assert_parse_err(&bad, PivError::WireFormat);
    }

    #[test]
    fn initial_health_is_auth_required() {
        let b = fresh_backend();
        assert_eq!(b.health(), PivHealthState::AuthRequired);
    }

    #[test]
    fn health_after_verify_is_ready() {
        let b = verified_backend();
        assert_eq!(b.health(), PivHealthState::Ready);
    }

    #[test]
    fn verify_pin_correct() {
        let mut b = fresh_backend();
        assert!(b.verify_pin(DEV_PIN).is_ok());
        assert!(b.verified);
        assert_eq!(b.pin_failures, 0);
    }

    #[test]
    fn verify_pin_wrong_increments_counter() {
        let mut b = fresh_backend();
        assert_eq!(b.verify_pin(b"wrong").unwrap_err(), PivError::AuthRequired);
        assert_eq!(b.pin_failures, 1);
        assert!(!b.verified);
        assert_eq!(b.verify_pin(b"wrong").unwrap_err(), PivError::AuthRequired);
        assert_eq!(b.pin_failures, 2);
    }

    #[test]
    fn pin_lockout_after_three_failures() {
        let mut b = fresh_backend();
        let _ = b.verify_pin(b"x");
        let _ = b.verify_pin(b"x");
        assert_eq!(b.verify_pin(b"x").unwrap_err(), PivError::PinLocked);
        // Even with the correct PIN, locked state persists.
        assert_eq!(b.verify_pin(DEV_PIN).unwrap_err(), PivError::PinLocked);
        assert_eq!(b.health(), PivHealthState::NotReady);
    }

    #[test]
    fn verify_pin_resets_counter_on_success() {
        let mut b = fresh_backend();
        let _ = b.verify_pin(b"x");
        let _ = b.verify_pin(b"x");
        assert_eq!(b.pin_failures, 2);
        assert!(b.verify_pin(DEV_PIN).is_ok());
        assert_eq!(b.pin_failures, 0);
    }

    #[test]
    fn list_slots_returns_four() {
        let b = fresh_backend();
        let list = b.list_slots();
        assert_eq!(list.count, 4);
        // 9C populated Ed25519
        assert_eq!(list.entries[1].slot, PivSlot::Signature);
        assert_eq!(list.entries[1].algo, PivAlgo::Ed25519);
        assert!(list.entries[1].populated);
        // 9D populated X25519
        assert_eq!(list.entries[2].slot, PivSlot::KeyManagement);
        assert_eq!(list.entries[2].algo, PivAlgo::X25519);
        assert!(list.entries[2].populated);
        // 9A empty
        assert!(!list.entries[0].populated);
        // 9E empty
        assert!(!list.entries[3].populated);
    }

    #[test]
    fn get_pubkey_signature_slot_no_pin_required() {
        // Real PIV pubkeys are readable without PIN verification —
        // mirror that in the dev backend.
        let b = fresh_backend();
        let pk = b.get_pubkey(PivSlot::Signature).expect("9C pubkey");
        assert_eq!(pk.algo, PivAlgo::Ed25519);
        assert_eq!(pk.len, 32);
        // Matches what's in the DPIV bundle.
        assert_eq!(pk.as_slice(), &b.ed25519_pk_bytes);
    }

    #[test]
    fn get_pubkey_key_management_slot() {
        let b = fresh_backend();
        let pk = b.get_pubkey(PivSlot::KeyManagement).expect("9D pubkey");
        assert_eq!(pk.algo, PivAlgo::X25519);
        assert_eq!(pk.len, 32);
        assert_eq!(pk.as_slice(), &b.x25519_pk_bytes);
    }

    #[test]
    fn get_pubkey_empty_slots_return_slot_empty() {
        let b = fresh_backend();
        assert_eq!(
            b.get_pubkey(PivSlot::Authentication).unwrap_err(),
            PivError::SlotEmpty
        );
        assert_eq!(
            b.get_pubkey(PivSlot::CardAuthentication).unwrap_err(),
            PivError::SlotEmpty
        );
    }

    #[test]
    fn sign_requires_pin() {
        let b = fresh_backend();
        assert_eq!(
            b.sign(PivSlot::Signature, b"msg").unwrap_err(),
            PivError::AuthRequired
        );
    }

    #[test]
    fn sign_verifies_under_advertised_pubkey() {
        let b = verified_backend();
        let msg = b"hello cambios FDE";
        let sig = b.sign(PivSlot::Signature, msg).expect("sign");
        let pk = b.get_pubkey(PivSlot::Signature).expect("9C pubkey");
        // Independently verify via ed25519-compact.
        let pk_obj = ed25519_compact::PublicKey::from_slice(pk.as_slice())
            .expect("pubkey parse");
        let sig_obj = ed25519_compact::Signature::from_slice(&sig.0)
            .expect("sig parse");
        pk_obj.verify(msg, &sig_obj).expect("signature must verify");
    }

    #[test]
    fn sign_wrong_slot_rejected() {
        let b = verified_backend();
        for slot in [
            PivSlot::Authentication,
            PivSlot::KeyManagement,
            PivSlot::CardAuthentication,
        ] {
            assert_eq!(
                b.sign(slot, b"msg").unwrap_err(),
                PivError::WrongAlgorithm
            );
        }
    }

    #[test]
    fn decrypt_requires_pin() {
        let b = fresh_backend();
        let mut out = [0u8; 32];
        assert_eq!(
            b.decrypt(PivSlot::KeyManagement, &[0u8; 32], &mut out)
                .unwrap_err(),
            PivError::AuthRequired
        );
    }

    #[test]
    fn decrypt_ecdh_roundtrip_against_independent_sender() {
        // Sender generates an ephemeral X25519 keypair, computes ECDH
        // against the backend's slot-9D public key, sends the ephemeral
        // pubkey as the "wrapped" payload, and expects the backend to
        // return the same shared secret.
        let b = verified_backend();
        let pk = b.get_pubkey(PivSlot::KeyManagement).expect("9D pk");
        let backend_x_pk =
            ed25519_compact::x25519::PublicKey::from_slice(pk.as_slice())
                .expect("backend x25519 pk parse");

        // Independent ephemeral keypair (derived from a fixed seed for
        // reproducibility; in the real flow this would be fresh
        // entropy per operation).
        let ephemeral_ed_seed = ed25519_compact::Seed::new([0x42u8; 32]);
        let ephemeral_ed_keypair = ed25519_compact::KeyPair::from_seed(ephemeral_ed_seed);
        let ephemeral_x_keypair =
            ed25519_compact::x25519::KeyPair::from_ed25519(&ephemeral_ed_keypair)
                .expect("eph X conversion");

        // Sender's view of the shared secret.
        let sender_shared = backend_x_pk
            .dh(&ephemeral_x_keypair.sk)
            .expect("sender ECDH");

        // Backend's view via the IPC contract.
        let wrapped = ephemeral_x_keypair.pk.as_ref();
        let mut out = [0u8; 32];
        let n = b
            .decrypt(PivSlot::KeyManagement, wrapped, &mut out)
            .expect("backend ECDH");
        assert_eq!(n, 32);
        assert_eq!(out, *sender_shared.as_ref());
    }

    #[test]
    fn decrypt_wrong_slot_rejected() {
        let b = verified_backend();
        let mut out = [0u8; 32];
        for slot in [
            PivSlot::Signature,
            PivSlot::Authentication,
            PivSlot::CardAuthentication,
        ] {
            assert_eq!(
                b.decrypt(slot, &[0u8; 32], &mut out).unwrap_err(),
                PivError::WrongAlgorithm
            );
        }
    }

    #[test]
    fn decrypt_wrong_wrapped_length_rejected() {
        let b = verified_backend();
        let mut out = [0u8; 32];
        assert_eq!(
            b.decrypt(PivSlot::KeyManagement, &[0u8; 31], &mut out)
                .unwrap_err(),
            PivError::Generic
        );
        assert_eq!(
            b.decrypt(PivSlot::KeyManagement, &[0u8; 33], &mut out)
                .unwrap_err(),
            PivError::Generic
        );
    }

    #[test]
    fn attest_returns_slot_empty() {
        let b = verified_backend();
        let mut out = [0u8; 256];
        assert_eq!(
            b.attest(PivSlot::Signature, &mut out).unwrap_err(),
            PivError::SlotEmpty
        );
    }

    #[test]
    fn status_byte_round_trip_unused_in_backend() {
        // Smoke test that PivStatus is reachable for downstream IPC
        // dispatch. Backend itself doesn't emit status bytes; that's
        // the IPC layer's job in A-iii.
        assert_eq!(PivStatus::Ok as u8, 0);
    }
}
