// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2024-2026 Jason Ricca

//! Antialiased bitmap font format + JetBrains Mono `BUILTIN_FONT_JBM`.
//!
//! Companion to [`crate::font`] (1-bit-per-pixel bitmap). `Font` is the
//! retro path — every glyph pixel is on or off, blits compose with no
//! background read. `AntialiasedFont` is the modern path — every glyph
//! pixel carries an alpha 0..=255 and the renderer alpha-blends against
//! the existing surface contents.
//!
//! ## Storage layout
//!
//! Each glyph is `cell_w × cell_h` consecutive bytes, row-major. One
//! byte per pixel = grayscale alpha. Glyphs cover a contiguous ASCII
//! range starting at `first`. Out-of-range characters render as a
//! blank cell that still advances the pen.
//!
//! ## Where the bytes come from
//!
//! `font_jbmono_data.rs` is generated by `tools/bake-font` from the
//! redistributable JetBrains Mono Regular TTF in `assets/fonts/`. The
//! TTF never enters the kernel image — the bake step turns it into a
//! `&'static [u8]` table at host-build time.

use crate::surface::Surface;
use crate::Color;

/// Antialiased monospace bitmap font. Storage and lookup are
/// monomorphic over the ASCII range (`first..first+num_glyphs`) so the
/// renderer can index by `(ch - first) * cell_w * cell_h` without a
/// table lookup.
pub struct AntialiasedFont {
    pub cell_w: u16,
    pub cell_h: u16,
    pub first: u8,
    pub num_glyphs: u8,
    pub data: &'static [u8],
}

impl AntialiasedFont {
    /// Returns the alpha byte slice for `ch`'s glyph cell, or `None`
    /// if the codepoint is outside the font's covered range.
    pub fn glyph(&self, ch: u8) -> Option<&'static [u8]> {
        if ch < self.first {
            return None;
        }
        let idx = (ch - self.first) as usize;
        if idx >= self.num_glyphs as usize {
            return None;
        }
        let cell_size = (self.cell_w as usize) * (self.cell_h as usize);
        let start = idx * cell_size;
        let end = start + cell_size;
        if end > self.data.len() {
            return None;
        }
        Some(&self.data[start..end])
    }
}

// JetBrains Mono Regular, baked at 24 px height into a 16×32 cell.
// Re-bake via the command in the data file's header.
#[path = "font_jbmono_data.rs"]
mod font_jbmono_data;

/// Built-in JetBrains Mono Regular at 16×32 cell. Covers ASCII
/// 0x20..=0x7F. See `font_jbmono_data.rs` for the byte table.
pub const BUILTIN_FONT_JBM: AntialiasedFont = AntialiasedFont {
    cell_w: font_jbmono_data::JBM_CELL_W,
    cell_h: font_jbmono_data::JBM_CELL_H,
    first: font_jbmono_data::JBM_FIRST,
    num_glyphs: font_jbmono_data::JBM_NUM_GLYPHS,
    data: font_jbmono_data::JBM_DATA,
};

// ============================================================================
// Rendering — alpha-blended glyph blit + draw_text_aa wrapper.
// ============================================================================

impl Surface<'_> {
    /// Draw `text` at `(x, y)` (top-left of first glyph cell) using
    /// `font` at full intensity `color`. Each glyph pixel's alpha is
    /// linear-blended against the surface's existing contents — so
    /// callers must pre-fill the cell band with the target background
    /// for the blend to land cleanly.
    pub fn draw_text_aa(&mut self, x: i32, y: i32, text: &str, color: Color, font: &AntialiasedFont) {
        let cw = font.cell_w as i32;
        let mut pen_x = x;
        for ch in text.as_bytes() {
            self.draw_glyph_aa(pen_x, y, *ch, color, font);
            pen_x = pen_x.saturating_add(cw);
        }
    }

    fn draw_glyph_aa(&mut self, x: i32, y: i32, ch: u8, color: Color, font: &AntialiasedFont) {
        let bytes = match font.glyph(ch) {
            Some(b) => b,
            None => return, // blank cell — pen still advanced by caller
        };
        let cw = font.cell_w as i32;
        let ch_h = font.cell_h as i32;
        for row in 0..ch_h {
            let py = y + row;
            let row_off = (row as usize) * (cw as usize);
            for col in 0..cw {
                let alpha = bytes[row_off + col as usize];
                if alpha == 0 {
                    continue; // common case — fast skip
                }
                if alpha == 0xFF {
                    self.set_pixel(x + col, py, color);
                } else {
                    self.blend_pixel(x + col, py, color, alpha);
                }
            }
        }
    }
}
