#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 Jason Ricca
"""
check-boot-panics: enforce ADR-021 Phase C — no `.expect()` /
`panic!()` / `unimplemented!()` / `todo!()` in kernel boot-path
init code.

Phases 021.B.1 – 021.B.3 migrated the eleven boot-path
panic/expect sites identified in ADR-021 to typed
`Result<(), BootError>` propagation. This lint prevents a new
one from appearing in the same scope without an exemption.

Scope: curated list of files that make up the boot init surface:
  - src/boot/**/*.rs               — boot-protocol adapters,
                                     BootInfo abstraction, initrd.
  - src/interrupts/mod.rs          — IDT / APIC / I/O APIC init.
  - src/arch/x86_64/apic.rs        — APIC enable + calibration.
  - src/arch/aarch64/{timer,gic}.rs — ARM timer + GIC init.
  - src/arch/riscv64/{timer,plic,entry,sbi}.rs — RISC-V init.

Runtime fault handlers (e.g. src/arch/riscv64/trap.rs) are
explicitly out of scope; kernel-mode fault recovery is deferred
per ADR-019.

Patterns flagged (case-sensitive):
  `.expect(`, `panic!(`, `unimplemented!(`, `todo!(`

Skips:
  - `#[cfg(test)]` / `mod tests` blocks (brace-depth walker).
  - `// BOOT_PANIC_OK:` exemption comment within 3 lines
    (above or on the same line).

Baseline exemptions live in `tools/check-boot-panics-baseline.txt`
— one record per line in `path:line:pattern` form. Today the
baseline is empty; any new entry means a regression relative to
ADR-021 Phase C.

Exit status:
  0 — no new sites
  1 — new sites flagged
  2 — repo root not found or baseline unreadable
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASELINE_PATH = ROOT / "tools" / "check-boot-panics-baseline.txt"

PATTERNS = [
    ("expect", re.compile(r"\.expect\s*\(")),
    ("panic", re.compile(r"\bpanic!\s*\(")),
    ("unimplemented", re.compile(r"\bunimplemented!\s*\(")),
    ("todo", re.compile(r"\btodo!\s*\(")),
]

EXEMPT_MARKER = re.compile(r"BOOT_PANIC_OK:")

# Curated scope. Directories recurse *.rs; individual files scan as-is.
SCAN_PATHS = [
    ("dir", "src/boot"),
    ("file", "src/interrupts/mod.rs"),
    ("file", "src/arch/x86_64/apic.rs"),
    ("file", "src/arch/aarch64/timer.rs"),
    ("file", "src/arch/aarch64/gic.rs"),
    ("file", "src/arch/riscv64/timer.rs"),
    ("file", "src/arch/riscv64/plic.rs"),
    ("file", "src/arch/riscv64/entry.rs"),
    ("file", "src/arch/riscv64/sbi.rs"),
]

CONTEXT_WINDOW = 3


def iter_scan_paths():
    for kind, rel in SCAN_PATHS:
        path = ROOT / rel
        if kind == "dir" and path.is_dir():
            yield from sorted(path.glob("**/*.rs"))
        elif kind == "file" and path.is_file():
            yield path


def in_test_context(lines, idx):
    window = lines[max(0, idx - 300):idx]
    in_test_mod = False
    brace_depth = 0
    for line in window:
        if re.search(r"#\[cfg\(test\)\]", line) or re.search(r"\bmod\s+tests\b", line):
            in_test_mod = True
        if in_test_mod:
            brace_depth += line.count("{") - line.count("}")
    return in_test_mod and brace_depth > 0


def has_exemption_near(lines, idx, window=CONTEXT_WINDOW):
    lo = max(0, idx - window)
    chunk = "\n".join(lines[lo:idx + 1])
    return bool(EXEMPT_MARKER.search(chunk))


def find_panics(path: Path):
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        # Strip line comments before searching for patterns so a // mention
        # of "panic!(..)" in prose doesn't flag.
        stripped = re.sub(r"//.*$", "", line)
        if not stripped.strip():
            continue
        for name, pat in PATTERNS:
            if pat.search(stripped):
                if in_test_context(lines, idx):
                    break
                if has_exemption_near(lines, idx):
                    break
                yield (idx + 1, name, line.rstrip())
                break  # one report per line


def load_baseline():
    if not BASELINE_PATH.is_file():
        return set()
    entries = set()
    for raw in BASELINE_PATH.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(":", 3)
        if len(parts) < 3:
            continue
        entries.add((parts[0], parts[1], parts[2]))
    return entries


def write_baseline(hits):
    header = [
        "# Auto-generated by `make update-boot-panics-baseline`.",
        "# Format: path:line:pattern (see tools/check-boot-panics.py).",
        "#",
        "# Expected state: empty — ADR-021 Phase C started from zero",
        "# after Phases B.1-B.3 migrated every boot-path panic/expect",
        "# to typed BootError propagation. Any non-comment line here",
        "# is a regression against ADR-021 that's been intentionally",
        "# accepted.",
        "",
    ]
    lines = header + [
        f"{rel}:{lineno}:{pat}" for rel, lineno, pat, _line in sorted(hits)
    ]
    BASELINE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main():
    if not ROOT.is_dir():
        print(f"repo root not found: {ROOT}", file=sys.stderr)
        return 2

    update_mode = "--update-baseline" in sys.argv

    baseline = load_baseline()
    new_violations = []
    all_hits = []

    for path in iter_scan_paths():
        rel = path.relative_to(ROOT).as_posix()
        for lineno, pat, line in find_panics(path):
            key = (rel, str(lineno), pat)
            all_hits.append((rel, lineno, pat, line))
            if key not in baseline:
                new_violations.append((rel, lineno, pat, line))

    if update_mode:
        write_baseline(all_hits)
        print(
            f"check-boot-panics: baseline written with {len(all_hits)} entries "
            f"→ {BASELINE_PATH.relative_to(ROOT)}"
        )
        return 0

    print(
        f"check-boot-panics: scanned; {len(all_hits)} total flagged, "
        f"{len(baseline)} baseline, {len(new_violations)} new"
    )

    if new_violations:
        print(
            f"\ncheck-boot-panics found {len(new_violations)} new "
            f"panic/expect site(s) in boot-path files:",
            file=sys.stderr,
        )
        for rel, lineno, pat, line in new_violations:
            print(f"  {rel}:{lineno}: [{pat}]", file=sys.stderr)
            print(f"    > {line.strip()[:140]}", file=sys.stderr)
        print(
            "\nBoot-path init must propagate failures as typed "
            "Result<(), BootError> per ADR-021. Fix by one of:",
            file=sys.stderr,
        )
        print("  (a) return Err(BootError::<variant>)? — preferred.", file=sys.stderr)
        print("  (b) add `// BOOT_PANIC_OK: <reason>` above the site if the", file=sys.stderr)
        print("      panic is genuinely unrecoverable and documented.", file=sys.stderr)
        print("  (c) append to tools/check-boot-panics-baseline.txt to", file=sys.stderr)
        print("      acknowledge a regression:", file=sys.stderr)
        for rel, lineno, pat, _ in new_violations[:5]:
            print(f"       {rel}:{lineno}:{pat}", file=sys.stderr)
        return 1

    print("check-boot-panics OK: no new sites")
    return 0


if __name__ == "__main__":
    sys.exit(main())
