#!/usr/bin/env python3
# Copyright (C) 2024-2026 Jason Ricca. All rights reserved.
"""
check-adrs: verify ADR cross-references and regenerate docs/adr/INDEX.md.

Walks docs/adr/*.md, extracts every "ADR-NNN" reference from ADR
content, verifies the referenced file exists, and flags references to
ADRs marked as Superseded. Also detects duplicate ADR numbers.

Regenerates docs/adr/INDEX.md from scanned metadata on every run.

Exit status:
  0 — all references resolve cleanly
  1 — one or more stale or invalid references found
  2 — ADR directory missing or unreadable

Scope: this lint covers ADR-to-ADR references only. References from
CLAUDE.md, STATUS.md, or other project docs are out of scope; if they
develop drift problems, extend this tool rather than adding a second.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = ROOT / "docs" / "adr"
INDEX_PATH = ADR_DIR / "INDEX.md"

ADR_FILE_RE = re.compile(r"^(\d{3})-.*\.md$")
REF_RE = re.compile(r"ADR-(\d{3})")
TITLE_RE = re.compile(r"^#\s+ADR-\d{3}[:\s]+(.+)$", re.MULTILINE)
STATUS_RE = re.compile(r"^-\s*\*\*Status:\*\*\s*(.+)$", re.MULTILINE)
DATE_RE = re.compile(r"^-\s*\*\*Date:\*\*\s*(.+)$", re.MULTILINE)


def scan():
    """Scan ADR files; return list of record dicts ordered by filename."""
    adrs = []
    for path in sorted(ADR_DIR.glob("*.md")):
        if path.name == "INDEX.md":
            continue
        m = ADR_FILE_RE.match(path.name)
        if not m:
            continue
        num = m.group(1)
        text = path.read_text(encoding="utf-8")
        title_m = TITLE_RE.search(text)
        status_m = STATUS_RE.search(text)
        date_m = DATE_RE.search(text)
        adrs.append({
            "num": num,
            "path": path,
            "text": text,
            "title": title_m.group(1).strip() if title_m else "(no title)",
            "status": status_m.group(1).strip() if status_m else "(unknown)",
            "date": date_m.group(1).strip() if date_m else "",
        })
    return adrs


def check_refs(adrs):
    """Flag stale references. Returns list of error strings."""
    errors = []
    by_num = {}
    for a in adrs:
        by_num.setdefault(a["num"], []).append(a)

    for a in adrs:
        seen = set()
        for ref_num in REF_RE.findall(a["text"]):
            if ref_num == a["num"] or ref_num in seen:
                continue
            seen.add(ref_num)
            if ref_num not in by_num:
                errors.append(
                    f"{a['path'].name}: references ADR-{ref_num} — "
                    f"no such ADR exists"
                )
                continue
            for target in by_num[ref_num]:
                if target["status"].lower().startswith("superseded"):
                    errors.append(
                        f"{a['path'].name}: references ADR-{ref_num} — "
                        f"target is {target['status']}"
                    )

    for num, entries in by_num.items():
        if len(entries) > 1:
            names = ", ".join(e["path"].name for e in entries)
            errors.append(f"duplicate ADR-{num}: {names}")

    return errors


def regenerate_index(adrs):
    """Rewrite docs/adr/INDEX.md from scanned metadata."""
    lines = [
        "<!--",
        "auto-generated by tools/check-adrs.py — do not edit by hand.",
        "run `make check-adrs` to regenerate.",
        "-->",
        "",
        "# ADR Index",
        "",
        "Canonical list of architecture decision records. Auto-generated "
        "from each ADR's header; run `make check-adrs` to refresh. "
        "Individual ADR files remain the source of truth for their "
        "decisions — this file is a directory, not a substitute.",
        "",
        "| # | Title | Status | Date |",
        "|---|---|---|---|",
    ]
    for a in adrs:
        title_link = f"[{a['title']}]({a['path'].name})"
        lines.append(
            f"| {a['num']} | {title_link} | {a['status']} | {a['date']} |"
        )
    lines.append("")
    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def main():
    if not ADR_DIR.is_dir():
        print(f"ADR directory not found: {ADR_DIR}", file=sys.stderr)
        return 2
    adrs = scan()
    errors = check_refs(adrs)
    regenerate_index(adrs)
    if errors:
        print(f"ADR check found {len(errors)} issue(s):", file=sys.stderr)
        for err in errors:
            print(f"  {err}", file=sys.stderr)
        print(f"(index regenerated anyway: {INDEX_PATH.relative_to(ROOT)})",
              file=sys.stderr)
        return 1
    print(f"ADR check OK: {len(adrs)} ADRs scanned")
    print(f"index regenerated: {INDEX_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
