#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 Jason Ricca
#
# gen-symbols.py — generate a machine-readable symbol index of the
# CambiOS kernel crate for AI-assisted development.
#
# Output: .symbols file at the repo root.
# Usage:  python3 tools/gen-symbols.py   OR   make symbols

import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
OUTPUT = REPO_ROOT / ".symbols"

# Patterns for Rust symbol definitions.
# Each tuple: (kind, compiled_regex, name_group_index)
PATTERNS = [
    ("struct", re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?struct\s+([A-Z]\w*)'), 1),
    ("enum",   re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?enum\s+([A-Z]\w*)'), 1),
    ("const",  re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?(?:const|static)\s+([A-Z_]\w*)\s*:'), 1),
    ("fn",     re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?(?:unsafe\s+)?(?:const\s+)?(?:extern\s+"[^"]*"\s+)?fn\s+([a-z_]\w*)'), 1),
    ("trait",  re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?trait\s+([A-Z]\w*)'), 1),
    ("mod",    re.compile(r'^\s*(?:pub(?:\(crate\))?\s+)?mod\s+([a-z_]\w*)'), 1),
]

# For consts, try to extract a simple value after '='
CONST_VALUE_RE = re.compile(r'=\s*(.+?)\s*;')


def extract_symbols(filepath: Path, relpath: str) -> list[str]:
    """Extract symbol lines from a single .rs file."""
    lines_out = []
    try:
        text = filepath.read_text(encoding="utf-8")
    except Exception:
        return lines_out

    for lineno, line in enumerate(text.splitlines(), start=1):
        for kind, pattern, group in PATTERNS:
            m = pattern.match(line)
            if not m:
                continue
            name = m.group(group)

            # Skip test modules — not useful for navigation
            if kind == "mod" and name == "tests":
                continue
            # Skip test functions
            if kind == "fn" and name.startswith("test_"):
                continue

            extra = ""
            if kind == "const":
                vm = CONST_VALUE_RE.search(line)
                if vm:
                    val = vm.group(1).strip()
                    if len(val) <= 50:
                        extra = f":{val}"

            lines_out.append(f"{kind}:{name}:{relpath}:{lineno}{extra}")
            break  # first match wins per line

    return lines_out


def main():
    if not SRC_DIR.is_dir():
        print(f"Error: {SRC_DIR} not found", file=sys.stderr)
        sys.exit(1)

    all_symbols: list[str] = []

    # Walk src/ in sorted order for deterministic output
    for filepath in sorted(SRC_DIR.rglob("*.rs")):
        relpath = str(filepath.relative_to(REPO_ROOT))
        all_symbols.extend(extract_symbols(filepath, relpath))

    # Write output
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(OUTPUT, "w") as f:
        f.write("# .symbols — auto-generated by tools/gen-symbols.py\n")
        f.write("# Format: KIND:NAME:FILE:LINE[:VALUE]\n")
        f.write("# Re-generate: make symbols\n")
        f.write("# Do NOT edit manually.\n")
        f.write("#\n")
        f.write(f"# Generated: {now}\n")
        f.write(f"# Total: {len(all_symbols)} symbols\n")
        f.write("#\n")
        for sym in all_symbols:
            f.write(sym + "\n")

    print(f"Generated {OUTPUT} ({len(all_symbols)} symbols)")


if __name__ == "__main__":
    main()
