#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 Jason Ricca
#
# gen-symbols.sh — generate a machine-readable symbol index of the
# ArcOS kernel crate for AI-assisted development.
#
# Output: .symbols file at the repo root, one line per symbol.
# Format: KIND:NAME:FILE:LINE[:EXTRA]
#
# The file is designed to be read by Claude Code at the start of a
# session to avoid dozens of grep calls for "where is X defined?"
# and "what line is this const on?" It replaces the manual line-
# number tracking in ASSUMPTIONS.md for the purpose of navigation.
#
# Usage:
#   ./tools/gen-symbols.sh          # writes .symbols
#   make symbols                    # same, via Makefile target
#
# This is a grep-based extractor, not a full parser. It works because
# ArcOS follows consistent naming conventions (pub struct, pub const,
# pub fn, etc.). It will miss:
# - Symbols inside macro expansions
# - Trait implementations (impl Foo for Bar)
# - Type aliases
# It will catch the ~95% of symbols that matter for navigation.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/.symbols"

# Header
cat > "$OUTPUT" << 'HEADER'
# .symbols — auto-generated by tools/gen-symbols.sh
# Format: KIND:NAME:FILE:LINE[:EXTRA]
# Re-generate: make symbols
# Do NOT edit manually — this file is overwritten on each run.
#
# KIND values:
#   struct    — struct definition (EXTRA = field count)
#   enum      — enum definition
#   const     — const or static (EXTRA = value if simple)
#   fn        — function definition
#   mod       — module declaration
#   trait     — trait definition
#   impl      — impl block (EXTRA = target type)
#   type      — type alias
HEADER

echo "#" >> "$OUTPUT"
echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$OUTPUT"
echo "#" >> "$OUTPUT"

# Find all .rs files under src/
find "$REPO_ROOT/src" -name '*.rs' -type f | sort | while read -r file; do
    # Make path relative to repo root
    relpath="${file#$REPO_ROOT/}"

    # Structs: pub struct Foo / struct Foo
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?struct\s\+[A-Z]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*struct\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/')
        echo "struct:$name:$relpath:$line" >> "$OUTPUT"
    done

    # Enums: pub enum Foo / enum Foo
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?enum\s\+[A-Z]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*enum\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/')
        echo "enum:$name:$relpath:$line" >> "$OUTPUT"
    done

    # Constants: pub const FOO / const FOO / pub static FOO
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?\(const\|static\)\s\+[A-Z_]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*\(const\|static\)\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\2/')
        # Try to extract simple value (= NUMBER or = "string")
        value=$(echo "$rest" | sed -n 's/.*=\s*\([^;]*\);.*/\1/p' | head -1 | xargs 2>/dev/null || true)
        if [ -n "$value" ] && [ ${#value} -le 40 ]; then
            echo "const:$name:$relpath:$line:$value" >> "$OUTPUT"
        else
            echo "const:$name:$relpath:$line" >> "$OUTPUT"
        fi
    done

    # Functions: pub fn foo / fn foo / pub(crate) fn foo
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?\(unsafe\s\+\)\?\(const\s\+\)\?fn\s\+[a-z_]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*fn\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/')
        echo "fn:$name:$relpath:$line" >> "$OUTPUT"
    done

    # Modules: pub mod foo / mod foo
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?mod\s\+[a-z_]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*mod\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/')
        # Skip #[cfg(test)] mod tests — not useful for navigation
        if [ "$name" != "tests" ]; then
            echo "mod:$name:$relpath:$line" >> "$OUTPUT"
        fi
    done

    # Traits: pub trait Foo / trait Foo
    grep -n '^\s*\(pub\(\s*(crate)\)\?\s\+\)\?trait\s\+[A-Z]' "$file" 2>/dev/null | while IFS=: read -r line rest; do
        name=$(echo "$rest" | sed 's/.*trait\s\+\([A-Za-z_][A-Za-z0-9_]*\).*/\1/')
        echo "trait:$name:$relpath:$line" >> "$OUTPUT"
    done

done

# Count
total=$(grep -c '^[a-z]' "$OUTPUT" || true)
echo "" >> "$OUTPUT"
echo "# Total: $total symbols" >> "$OUTPUT"

echo "Generated $OUTPUT ($total symbols)"
